@startuml
package "Gestão de Pedidos e Contratos" {
    [Pedido] as Pedido
    [Contrato] as Contrato
    [Automóvel] as Automóvel
    [Crédito] as Crédito

    Pedido -- Contrato : "Gera"
    Pedido -- Automóvel : "Inclui"
    Contrato -- Automóvel : "Referência"
    Contrato -- Crédito : "Associado"
}

package "Entidades" {
    [Cliente] as Cliente
    [Agente] as Agente

    Cliente -- Pedido : "Faz"
    Agente -- Pedido : "Avalia"
    Agente -- Contrato : "Gerencia"
    Agente -- Crédito : "Concede"
}

Pedido -[hidden]-> Contrato
Pedido -[hidden]-> Automóvel
Contrato -[hidden]-> Automóvel
Contrato -[hidden]-> Crédito

Cliente -[hidden]-> Pedido
Agente -[hidden]-> Pedido
Agente -[hidden]-> Contrato
Agente -[hidden]-> Crédito

@enduml
